### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by jolebas** [LPology/Simple-Ajax-Uploader#218]
As of today the button isn't clickable anymore.
Please see detail of issue raised on Stack Overflow https://stackoverflow.com/questions/57802970/simple-ajax-uploader-plugin-stopped-working

**Comment by weatherbell** [comment]
Yes - it needs to not create that overlay.

**Comment by DimNS** [comment]
Confirm. The same thing happened yesterday to me, the plugin stopped working. This happened right after the last Update of Chromium, in Firefox works

**Comment by floor12** [comment]
Resize of browser window fixes this problem until page refresh )

**Comment by persabio** [comment]
Now on the bootom browser i have big space (after change position to relative). I changed font fontSize from 480px to 0px, is better but when i click button big space return. Please help.

**Comment by LPology** [comment]
Pull request has been merged. I made an additional change which should fix the issue with adding additional space to bottom of page and bumped to 2.6.4.

@persabio Upgrade to newest version 2.6.4 which should fix the big space.

**Comment by LPology** [comment]
Interesting to note that at least one older version (2.5.5) does not appear to be affected by the issue that caused this problem.

**Comment by LPology** [comment]
Just pushed another change and cut release 2.6.6. This should resolve all problems with this, so I'm closing this issue. 

Anyone feel free to reopen or create a new issue if you encounter further problems. Thanks everyone for your input, feedback, and help, especially @mfurlend for the pull request.

**Comment by DimNS** [comment]
@LPology you forgot to do npm publish
![2019-09-09_10-39-38](https://user-images.githubusercontent.com/8703922/64505707-400aa680-d2ee-11e9-953a-a6252fc64cd2.png)

**Comment by LPology** [comment]
I actually do not own the npm package. I reached out to the person who owns it, so hopefully I can take over and then publish.

**Comment by LPology** [comment]
I am now the owner of the npm package and have just pushed an update for version 2.6.6:

https://www.npmjs.com/package/simple-ajax-uploader

Resolving.
